// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: ensemble.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityRequest) Reset() {
	*x = GetIdentityRequest{}
	mi := &file_ensemble_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityRequest) ProtoMessage() {}

func (x *GetIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{0}
}

type GetIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityResponse) Reset() {
	*x = GetIdentityResponse{}
	mi := &file_ensemble_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityResponse) ProtoMessage() {}

func (x *GetIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetIdentityResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{1}
}

func (x *GetIdentityResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetIdentityResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_ensemble_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{2}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorState      string                 `protobuf:"bytes,1,opt,name=tor_state,json=torState,proto3" json:"tor_state,omitempty"` // "bootstrapping", "ready", "disabled"
	PeerCount     int32                  `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	OnionAddr     string                 `protobuf:"bytes,3,opt,name=onion_addr,json=onionAddr,proto3" json:"onion_addr,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,4,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	RtSize        int32                  `protobuf:"varint,5,opt,name=rt_size,json=rtSize,proto3" json:"rt_size,omitempty"` // routing table size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_ensemble_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetTorState() string {
	if x != nil {
		return x.TorState
	}
	return ""
}

func (x *GetStatusResponse) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *GetStatusResponse) GetOnionAddr() string {
	if x != nil {
		return x.OnionAddr
	}
	return ""
}

func (x *GetStatusResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *GetStatusResponse) GetRtSize() int32 {
	if x != nil {
		return x.RtSize
	}
	return 0
}

type ListContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsRequest) Reset() {
	*x = ListContactsRequest{}
	mi := &file_ensemble_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsRequest) ProtoMessage() {}

func (x *ListContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsRequest.ProtoReflect.Descriptor instead.
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{4}
}

type ListContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*ContactInfo         `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsResponse) Reset() {
	*x = ListContactsResponse{}
	mi := &file_ensemble_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsResponse) ProtoMessage() {}

func (x *ListContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsResponse.ProtoReflect.Descriptor instead.
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{5}
}

func (x *ListContactsResponse) GetContacts() []*ContactInfo {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type ContactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	OnionAddress  string                 `protobuf:"bytes,4,opt,name=onion_address,json=onionAddress,proto3" json:"onion_address,omitempty"`
	AddedAt       int64                  `protobuf:"varint,5,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`    // Unix millis
	LastSeen      int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // Unix millis
	Online        bool                   `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_ensemble_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{6}
}

func (x *ContactInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ContactInfo) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ContactInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ContactInfo) GetOnionAddress() string {
	if x != nil {
		return x.OnionAddress
	}
	return ""
}

func (x *ContactInfo) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

func (x *ContactInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *ContactInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type AddContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContactRequest) Reset() {
	*x = AddContactRequest{}
	mi := &file_ensemble_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContactRequest) ProtoMessage() {}

func (x *AddContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContactRequest.ProtoReflect.Descriptor instead.
func (*AddContactRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{7}
}

func (x *AddContactRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddContactRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *AddContactRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type AddContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContactResponse) Reset() {
	*x = AddContactResponse{}
	mi := &file_ensemble_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContactResponse) ProtoMessage() {}

func (x *AddContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContactResponse.ProtoReflect.Descriptor instead.
func (*AddContactResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{8}
}

type RemoveContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContactRequest) Reset() {
	*x = RemoveContactRequest{}
	mi := &file_ensemble_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContactRequest) ProtoMessage() {}

func (x *RemoveContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContactRequest.ProtoReflect.Descriptor instead.
func (*RemoveContactRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveContactRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RemoveContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContactResponse) Reset() {
	*x = RemoveContactResponse{}
	mi := &file_ensemble_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContactResponse) ProtoMessage() {}

func (x *RemoveContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContactResponse.ProtoReflect.Descriptor instead.
func (*RemoveContactResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{10}
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // peer's ensemble address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_ensemble_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_ensemble_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{12}
}

func (x *ConnectResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AcceptConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // requester's address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptConnectionRequest) Reset() {
	*x = AcceptConnectionRequest{}
	mi := &file_ensemble_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptConnectionRequest) ProtoMessage() {}

func (x *AcceptConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptConnectionRequest.ProtoReflect.Descriptor instead.
func (*AcceptConnectionRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{13}
}

func (x *AcceptConnectionRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AcceptConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptConnectionResponse) Reset() {
	*x = AcceptConnectionResponse{}
	mi := &file_ensemble_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptConnectionResponse) ProtoMessage() {}

func (x *AcceptConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptConnectionResponse.ProtoReflect.Descriptor instead.
func (*AcceptConnectionResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{14}
}

type RejectConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectConnectionRequest) Reset() {
	*x = RejectConnectionRequest{}
	mi := &file_ensemble_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectConnectionRequest) ProtoMessage() {}

func (x *RejectConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectConnectionRequest.ProtoReflect.Descriptor instead.
func (*RejectConnectionRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{15}
}

func (x *RejectConnectionRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RejectConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectConnectionResponse) Reset() {
	*x = RejectConnectionResponse{}
	mi := &file_ensemble_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectConnectionResponse) ProtoMessage() {}

func (x *RejectConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectConnectionResponse.ProtoReflect.Descriptor instead.
func (*RejectConnectionResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{16}
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // recipient's address
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_ensemble_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{17}
}

func (x *SendMessageRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_ensemble_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{18}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // recipient's address
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_ensemble_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{19}
}

func (x *SendFileRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SendFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type TransferProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	SentBytes     uint64                 `protobuf:"varint,4,opt,name=sent_bytes,json=sentBytes,proto3" json:"sent_bytes,omitempty"`
	Percent       float32                `protobuf:"fixed32,5,opt,name=percent,proto3" json:"percent,omitempty"`
	Complete      bool                   `protobuf:"varint,6,opt,name=complete,proto3" json:"complete,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferProgress) Reset() {
	*x = TransferProgress{}
	mi := &file_ensemble_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferProgress) ProtoMessage() {}

func (x *TransferProgress) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferProgress.ProtoReflect.Descriptor instead.
func (*TransferProgress) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{20}
}

func (x *TransferProgress) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferProgress) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TransferProgress) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *TransferProgress) GetSentBytes() uint64 {
	if x != nil {
		return x.SentBytes
	}
	return 0
}

func (x *TransferProgress) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *TransferProgress) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *TransferProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AcceptFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	SavePath      string                 `protobuf:"bytes,2,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"` // where to save the file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFileRequest) Reset() {
	*x = AcceptFileRequest{}
	mi := &file_ensemble_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFileRequest) ProtoMessage() {}

func (x *AcceptFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFileRequest.ProtoReflect.Descriptor instead.
func (*AcceptFileRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{21}
}

func (x *AcceptFileRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *AcceptFileRequest) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

type AcceptFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFileResponse) Reset() {
	*x = AcceptFileResponse{}
	mi := &file_ensemble_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFileResponse) ProtoMessage() {}

func (x *AcceptFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFileResponse.ProtoReflect.Descriptor instead.
func (*AcceptFileResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{22}
}

type RejectFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFileRequest) Reset() {
	*x = RejectFileRequest{}
	mi := &file_ensemble_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFileRequest) ProtoMessage() {}

func (x *RejectFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFileRequest.ProtoReflect.Descriptor instead.
func (*RejectFileRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{23}
}

func (x *RejectFileRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type RejectFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFileResponse) Reset() {
	*x = RejectFileResponse{}
	mi := &file_ensemble_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFileResponse) ProtoMessage() {}

func (x *RejectFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFileResponse.ProtoReflect.Descriptor instead.
func (*RejectFileResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{24}
}

type AddNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnionAddress  string                 `protobuf:"bytes,1,opt,name=onion_address,json=onionAddress,proto3" json:"onion_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_ensemble_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{25}
}

func (x *AddNodeRequest) GetOnionAddress() string {
	if x != nil {
		return x.OnionAddress
	}
	return ""
}

type AddNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeersFound    int32                  `protobuf:"varint,1,opt,name=peers_found,json=peersFound,proto3" json:"peers_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_ensemble_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{26}
}

func (x *AddNodeResponse) GetPeersFound() int32 {
	if x != nil {
		return x.PeersFound
	}
	return 0
}

type GetDebugInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDebugInfoRequest) Reset() {
	*x = GetDebugInfoRequest{}
	mi := &file_ensemble_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebugInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugInfoRequest) ProtoMessage() {}

func (x *GetDebugInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebugInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDebugInfoRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{27}
}

type GetDebugInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RtSize        int32                  `protobuf:"varint,1,opt,name=rt_size,json=rtSize,proto3" json:"rt_size,omitempty"`
	RtPeers       []*DHTNode             `protobuf:"bytes,2,rep,name=rt_peers,json=rtPeers,proto3" json:"rt_peers,omitempty"`
	Connections   []*PeerState           `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
	OnionAddr     string                 `protobuf:"bytes,4,opt,name=onion_addr,json=onionAddr,proto3" json:"onion_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDebugInfoResponse) Reset() {
	*x = GetDebugInfoResponse{}
	mi := &file_ensemble_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebugInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugInfoResponse) ProtoMessage() {}

func (x *GetDebugInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebugInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDebugInfoResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{28}
}

func (x *GetDebugInfoResponse) GetRtSize() int32 {
	if x != nil {
		return x.RtSize
	}
	return 0
}

func (x *GetDebugInfoResponse) GetRtPeers() []*DHTNode {
	if x != nil {
		return x.RtPeers
	}
	return nil
}

func (x *GetDebugInfoResponse) GetConnections() []*PeerState {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *GetDebugInfoResponse) GetOnionAddr() string {
	if x != nil {
		return x.OnionAddr
	}
	return ""
}

type DHTNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OnionAddr     string                 `protobuf:"bytes,2,opt,name=onion_addr,json=onionAddr,proto3" json:"onion_addr,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // Unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DHTNode) Reset() {
	*x = DHTNode{}
	mi := &file_ensemble_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DHTNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHTNode) ProtoMessage() {}

func (x *DHTNode) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHTNode.ProtoReflect.Descriptor instead.
func (*DHTNode) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{29}
}

func (x *DHTNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DHTNode) GetOnionAddr() string {
	if x != nil {
		return x.OnionAddr
	}
	return ""
}

func (x *DHTNode) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type PeerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerState) Reset() {
	*x = PeerState{}
	mi := &file_ensemble_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerState) ProtoMessage() {}

func (x *PeerState) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerState.ProtoReflect.Descriptor instead.
func (*PeerState) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{30}
}

func (x *PeerState) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PeerState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_ensemble_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{31}
}

type DaemonEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // event type name
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded event data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonEvent) Reset() {
	*x = DaemonEvent{}
	mi := &file_ensemble_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonEvent) ProtoMessage() {}

func (x *DaemonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonEvent.ProtoReflect.Descriptor instead.
func (*DaemonEvent) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{32}
}

func (x *DaemonEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DaemonEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_ensemble_proto protoreflect.FileDescriptor

const file_ensemble_proto_rawDesc = "" +
	"\n" +
	"\x0eensemble.proto\x12\fensemble.api\"\x14\n" +
	"\x12GetIdentityRequest\"N\n" +
	"\x13GetIdentityResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\x12\n" +
	"\x10GetStatusRequest\"\xa4\x01\n" +
	"\x11GetStatusResponse\x12\x1b\n" +
	"\ttor_state\x18\x01 \x01(\tR\btorState\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x05R\tpeerCount\x12\x1d\n" +
	"\n" +
	"onion_addr\x18\x03 \x01(\tR\tonionAddr\x12\x1b\n" +
	"\tuptime_ms\x18\x04 \x01(\x03R\buptimeMs\x12\x17\n" +
	"\art_size\x18\x05 \x01(\x05R\x06rtSize\"\x15\n" +
	"\x13ListContactsRequest\"M\n" +
	"\x14ListContactsResponse\x125\n" +
	"\bcontacts\x18\x01 \x03(\v2\x19.ensemble.api.ContactInfoR\bcontacts\"\xd1\x01\n" +
	"\vContactInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12#\n" +
	"\ronion_address\x18\x04 \x01(\tR\fonionAddress\x12\x19\n" +
	"\badded_at\x18\x05 \x01(\x03R\aaddedAt\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\x12\x16\n" +
	"\x06online\x18\a \x01(\bR\x06online\"b\n" +
	"\x11AddContactRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"\x14\n" +
	"\x12AddContactResponse\"0\n" +
	"\x14RemoveContactRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x17\n" +
	"\x15RemoveContactResponse\"*\n" +
	"\x0eConnectRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"G\n" +
	"\x0fConnectResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x17AcceptConnectionRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x1a\n" +
	"\x18AcceptConnectionResponse\"3\n" +
	"\x17RejectConnectionRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x1a\n" +
	"\x18RejectConnectionResponse\"B\n" +
	"\x12SendMessageRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"4\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"H\n" +
	"\x0fSendFileRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\"\xdb\x01\n" +
	"\x10TransferProgress\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"sent_bytes\x18\x04 \x01(\x04R\tsentBytes\x12\x18\n" +
	"\apercent\x18\x05 \x01(\x02R\apercent\x12\x1a\n" +
	"\bcomplete\x18\x06 \x01(\bR\bcomplete\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"Q\n" +
	"\x11AcceptFileRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1b\n" +
	"\tsave_path\x18\x02 \x01(\tR\bsavePath\"\x14\n" +
	"\x12AcceptFileResponse\"4\n" +
	"\x11RejectFileRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"\x14\n" +
	"\x12RejectFileResponse\"5\n" +
	"\x0eAddNodeRequest\x12#\n" +
	"\ronion_address\x18\x01 \x01(\tR\fonionAddress\"2\n" +
	"\x0fAddNodeResponse\x12\x1f\n" +
	"\vpeers_found\x18\x01 \x01(\x05R\n" +
	"peersFound\"\x15\n" +
	"\x13GetDebugInfoRequest\"\xbb\x01\n" +
	"\x14GetDebugInfoResponse\x12\x17\n" +
	"\art_size\x18\x01 \x01(\x05R\x06rtSize\x120\n" +
	"\brt_peers\x18\x02 \x03(\v2\x15.ensemble.api.DHTNodeR\artPeers\x129\n" +
	"\vconnections\x18\x03 \x03(\v2\x17.ensemble.api.PeerStateR\vconnections\x12\x1d\n" +
	"\n" +
	"onion_addr\x18\x04 \x01(\tR\tonionAddr\"_\n" +
	"\aDHTNode\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"onion_addr\x18\x02 \x01(\tR\tonionAddr\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\"Q\n" +
	"\tPeerState\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x12\n" +
	"\x10SubscribeRequest\";\n" +
	"\vDaemonEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload2\xef\t\n" +
	"\x0fEnsembleService\x12R\n" +
	"\vGetIdentity\x12 .ensemble.api.GetIdentityRequest\x1a!.ensemble.api.GetIdentityResponse\x12L\n" +
	"\tGetStatus\x12\x1e.ensemble.api.GetStatusRequest\x1a\x1f.ensemble.api.GetStatusResponse\x12U\n" +
	"\fListContacts\x12!.ensemble.api.ListContactsRequest\x1a\".ensemble.api.ListContactsResponse\x12O\n" +
	"\n" +
	"AddContact\x12\x1f.ensemble.api.AddContactRequest\x1a .ensemble.api.AddContactResponse\x12X\n" +
	"\rRemoveContact\x12\".ensemble.api.RemoveContactRequest\x1a#.ensemble.api.RemoveContactResponse\x12F\n" +
	"\aConnect\x12\x1c.ensemble.api.ConnectRequest\x1a\x1d.ensemble.api.ConnectResponse\x12a\n" +
	"\x10AcceptConnection\x12%.ensemble.api.AcceptConnectionRequest\x1a&.ensemble.api.AcceptConnectionResponse\x12a\n" +
	"\x10RejectConnection\x12%.ensemble.api.RejectConnectionRequest\x1a&.ensemble.api.RejectConnectionResponse\x12R\n" +
	"\vSendMessage\x12 .ensemble.api.SendMessageRequest\x1a!.ensemble.api.SendMessageResponse\x12K\n" +
	"\bSendFile\x12\x1d.ensemble.api.SendFileRequest\x1a\x1e.ensemble.api.TransferProgress0\x01\x12O\n" +
	"\n" +
	"AcceptFile\x12\x1f.ensemble.api.AcceptFileRequest\x1a .ensemble.api.AcceptFileResponse\x12O\n" +
	"\n" +
	"RejectFile\x12\x1f.ensemble.api.RejectFileRequest\x1a .ensemble.api.RejectFileResponse\x12F\n" +
	"\aAddNode\x12\x1c.ensemble.api.AddNodeRequest\x1a\x1d.ensemble.api.AddNodeResponse\x12U\n" +
	"\fGetDebugInfo\x12!.ensemble.api.GetDebugInfoRequest\x1a\".ensemble.api.GetDebugInfoResponse\x12H\n" +
	"\tSubscribe\x12\x1e.ensemble.api.SubscribeRequest\x1a\x19.ensemble.api.DaemonEvent0\x01B#Z!github.com/boxsie/ensemble/api/pbb\x06proto3"

var (
	file_ensemble_proto_rawDescOnce sync.Once
	file_ensemble_proto_rawDescData []byte
)

func file_ensemble_proto_rawDescGZIP() []byte {
	file_ensemble_proto_rawDescOnce.Do(func() {
		file_ensemble_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ensemble_proto_rawDesc), len(file_ensemble_proto_rawDesc)))
	})
	return file_ensemble_proto_rawDescData
}

var file_ensemble_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_ensemble_proto_goTypes = []any{
	(*GetIdentityRequest)(nil),       // 0: ensemble.api.GetIdentityRequest
	(*GetIdentityResponse)(nil),      // 1: ensemble.api.GetIdentityResponse
	(*GetStatusRequest)(nil),         // 2: ensemble.api.GetStatusRequest
	(*GetStatusResponse)(nil),        // 3: ensemble.api.GetStatusResponse
	(*ListContactsRequest)(nil),      // 4: ensemble.api.ListContactsRequest
	(*ListContactsResponse)(nil),     // 5: ensemble.api.ListContactsResponse
	(*ContactInfo)(nil),              // 6: ensemble.api.ContactInfo
	(*AddContactRequest)(nil),        // 7: ensemble.api.AddContactRequest
	(*AddContactResponse)(nil),       // 8: ensemble.api.AddContactResponse
	(*RemoveContactRequest)(nil),     // 9: ensemble.api.RemoveContactRequest
	(*RemoveContactResponse)(nil),    // 10: ensemble.api.RemoveContactResponse
	(*ConnectRequest)(nil),           // 11: ensemble.api.ConnectRequest
	(*ConnectResponse)(nil),          // 12: ensemble.api.ConnectResponse
	(*AcceptConnectionRequest)(nil),  // 13: ensemble.api.AcceptConnectionRequest
	(*AcceptConnectionResponse)(nil), // 14: ensemble.api.AcceptConnectionResponse
	(*RejectConnectionRequest)(nil),  // 15: ensemble.api.RejectConnectionRequest
	(*RejectConnectionResponse)(nil), // 16: ensemble.api.RejectConnectionResponse
	(*SendMessageRequest)(nil),       // 17: ensemble.api.SendMessageRequest
	(*SendMessageResponse)(nil),      // 18: ensemble.api.SendMessageResponse
	(*SendFileRequest)(nil),          // 19: ensemble.api.SendFileRequest
	(*TransferProgress)(nil),         // 20: ensemble.api.TransferProgress
	(*AcceptFileRequest)(nil),        // 21: ensemble.api.AcceptFileRequest
	(*AcceptFileResponse)(nil),       // 22: ensemble.api.AcceptFileResponse
	(*RejectFileRequest)(nil),        // 23: ensemble.api.RejectFileRequest
	(*RejectFileResponse)(nil),       // 24: ensemble.api.RejectFileResponse
	(*AddNodeRequest)(nil),           // 25: ensemble.api.AddNodeRequest
	(*AddNodeResponse)(nil),          // 26: ensemble.api.AddNodeResponse
	(*GetDebugInfoRequest)(nil),      // 27: ensemble.api.GetDebugInfoRequest
	(*GetDebugInfoResponse)(nil),     // 28: ensemble.api.GetDebugInfoResponse
	(*DHTNode)(nil),                  // 29: ensemble.api.DHTNode
	(*PeerState)(nil),                // 30: ensemble.api.PeerState
	(*SubscribeRequest)(nil),         // 31: ensemble.api.SubscribeRequest
	(*DaemonEvent)(nil),              // 32: ensemble.api.DaemonEvent
}
var file_ensemble_proto_depIdxs = []int32{
	6,  // 0: ensemble.api.ListContactsResponse.contacts:type_name -> ensemble.api.ContactInfo
	29, // 1: ensemble.api.GetDebugInfoResponse.rt_peers:type_name -> ensemble.api.DHTNode
	30, // 2: ensemble.api.GetDebugInfoResponse.connections:type_name -> ensemble.api.PeerState
	0,  // 3: ensemble.api.EnsembleService.GetIdentity:input_type -> ensemble.api.GetIdentityRequest
	2,  // 4: ensemble.api.EnsembleService.GetStatus:input_type -> ensemble.api.GetStatusRequest
	4,  // 5: ensemble.api.EnsembleService.ListContacts:input_type -> ensemble.api.ListContactsRequest
	7,  // 6: ensemble.api.EnsembleService.AddContact:input_type -> ensemble.api.AddContactRequest
	9,  // 7: ensemble.api.EnsembleService.RemoveContact:input_type -> ensemble.api.RemoveContactRequest
	11, // 8: ensemble.api.EnsembleService.Connect:input_type -> ensemble.api.ConnectRequest
	13, // 9: ensemble.api.EnsembleService.AcceptConnection:input_type -> ensemble.api.AcceptConnectionRequest
	15, // 10: ensemble.api.EnsembleService.RejectConnection:input_type -> ensemble.api.RejectConnectionRequest
	17, // 11: ensemble.api.EnsembleService.SendMessage:input_type -> ensemble.api.SendMessageRequest
	19, // 12: ensemble.api.EnsembleService.SendFile:input_type -> ensemble.api.SendFileRequest
	21, // 13: ensemble.api.EnsembleService.AcceptFile:input_type -> ensemble.api.AcceptFileRequest
	23, // 14: ensemble.api.EnsembleService.RejectFile:input_type -> ensemble.api.RejectFileRequest
	25, // 15: ensemble.api.EnsembleService.AddNode:input_type -> ensemble.api.AddNodeRequest
	27, // 16: ensemble.api.EnsembleService.GetDebugInfo:input_type -> ensemble.api.GetDebugInfoRequest
	31, // 17: ensemble.api.EnsembleService.Subscribe:input_type -> ensemble.api.SubscribeRequest
	1,  // 18: ensemble.api.EnsembleService.GetIdentity:output_type -> ensemble.api.GetIdentityResponse
	3,  // 19: ensemble.api.EnsembleService.GetStatus:output_type -> ensemble.api.GetStatusResponse
	5,  // 20: ensemble.api.EnsembleService.ListContacts:output_type -> ensemble.api.ListContactsResponse
	8,  // 21: ensemble.api.EnsembleService.AddContact:output_type -> ensemble.api.AddContactResponse
	10, // 22: ensemble.api.EnsembleService.RemoveContact:output_type -> ensemble.api.RemoveContactResponse
	12, // 23: ensemble.api.EnsembleService.Connect:output_type -> ensemble.api.ConnectResponse
	14, // 24: ensemble.api.EnsembleService.AcceptConnection:output_type -> ensemble.api.AcceptConnectionResponse
	16, // 25: ensemble.api.EnsembleService.RejectConnection:output_type -> ensemble.api.RejectConnectionResponse
	18, // 26: ensemble.api.EnsembleService.SendMessage:output_type -> ensemble.api.SendMessageResponse
	20, // 27: ensemble.api.EnsembleService.SendFile:output_type -> ensemble.api.TransferProgress
	22, // 28: ensemble.api.EnsembleService.AcceptFile:output_type -> ensemble.api.AcceptFileResponse
	24, // 29: ensemble.api.EnsembleService.RejectFile:output_type -> ensemble.api.RejectFileResponse
	26, // 30: ensemble.api.EnsembleService.AddNode:output_type -> ensemble.api.AddNodeResponse
	28, // 31: ensemble.api.EnsembleService.GetDebugInfo:output_type -> ensemble.api.GetDebugInfoResponse
	32, // 32: ensemble.api.EnsembleService.Subscribe:output_type -> ensemble.api.DaemonEvent
	18, // [18:33] is the sub-list for method output_type
	3,  // [3:18] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_ensemble_proto_init() }
func file_ensemble_proto_init() {
	if File_ensemble_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ensemble_proto_rawDesc), len(file_ensemble_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ensemble_proto_goTypes,
		DependencyIndexes: file_ensemble_proto_depIdxs,
		MessageInfos:      file_ensemble_proto_msgTypes,
	}.Build()
	File_ensemble_proto = out.File
	file_ensemble_proto_goTypes = nil
	file_ensemble_proto_depIdxs = nil
}
