// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: ensemble.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ACL int32

const (
	ACL_ACL_PUBLIC    ACL = 0
	ACL_ACL_CONTACTS  ACL = 1
	ACL_ACL_ALLOWLIST ACL = 2
)

// Enum value maps for ACL.
var (
	ACL_name = map[int32]string{
		0: "ACL_PUBLIC",
		1: "ACL_CONTACTS",
		2: "ACL_ALLOWLIST",
	}
	ACL_value = map[string]int32{
		"ACL_PUBLIC":    0,
		"ACL_CONTACTS":  1,
		"ACL_ALLOWLIST": 2,
	}
)

func (x ACL) Enum() *ACL {
	p := new(ACL)
	*p = x
	return p
}

func (x ACL) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACL) Descriptor() protoreflect.EnumDescriptor {
	return file_ensemble_proto_enumTypes[0].Descriptor()
}

func (ACL) Type() protoreflect.EnumType {
	return &file_ensemble_proto_enumTypes[0]
}

func (x ACL) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACL.Descriptor instead.
func (ACL) EnumDescriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{0}
}

type GetIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityRequest) Reset() {
	*x = GetIdentityRequest{}
	mi := &file_ensemble_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityRequest) ProtoMessage() {}

func (x *GetIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{0}
}

type GetIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityResponse) Reset() {
	*x = GetIdentityResponse{}
	mi := &file_ensemble_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityResponse) ProtoMessage() {}

func (x *GetIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetIdentityResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{1}
}

func (x *GetIdentityResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetIdentityResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_ensemble_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{2}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorState      string                 `protobuf:"bytes,1,opt,name=tor_state,json=torState,proto3" json:"tor_state,omitempty"` // "bootstrapping", "ready", "disabled"
	PeerCount     int32                  `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	OnionAddr     string                 `protobuf:"bytes,3,opt,name=onion_addr,json=onionAddr,proto3" json:"onion_addr,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,4,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	RtSize        int32                  `protobuf:"varint,5,opt,name=rt_size,json=rtSize,proto3" json:"rt_size,omitempty"` // routing table size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_ensemble_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetTorState() string {
	if x != nil {
		return x.TorState
	}
	return ""
}

func (x *GetStatusResponse) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *GetStatusResponse) GetOnionAddr() string {
	if x != nil {
		return x.OnionAddr
	}
	return ""
}

func (x *GetStatusResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *GetStatusResponse) GetRtSize() int32 {
	if x != nil {
		return x.RtSize
	}
	return 0
}

type ListContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsRequest) Reset() {
	*x = ListContactsRequest{}
	mi := &file_ensemble_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsRequest) ProtoMessage() {}

func (x *ListContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsRequest.ProtoReflect.Descriptor instead.
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{4}
}

type ListContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*ContactInfo         `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsResponse) Reset() {
	*x = ListContactsResponse{}
	mi := &file_ensemble_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsResponse) ProtoMessage() {}

func (x *ListContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsResponse.ProtoReflect.Descriptor instead.
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{5}
}

func (x *ListContactsResponse) GetContacts() []*ContactInfo {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type ContactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	OnionAddress  string                 `protobuf:"bytes,4,opt,name=onion_address,json=onionAddress,proto3" json:"onion_address,omitempty"`
	AddedAt       int64                  `protobuf:"varint,5,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`    // Unix millis
	LastSeen      int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // Unix millis
	Online        bool                   `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_ensemble_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{6}
}

func (x *ContactInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ContactInfo) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ContactInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ContactInfo) GetOnionAddress() string {
	if x != nil {
		return x.OnionAddress
	}
	return ""
}

func (x *ContactInfo) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

func (x *ContactInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *ContactInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type AddContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContactRequest) Reset() {
	*x = AddContactRequest{}
	mi := &file_ensemble_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContactRequest) ProtoMessage() {}

func (x *AddContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContactRequest.ProtoReflect.Descriptor instead.
func (*AddContactRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{7}
}

func (x *AddContactRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddContactRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *AddContactRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type AddContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContactResponse) Reset() {
	*x = AddContactResponse{}
	mi := &file_ensemble_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContactResponse) ProtoMessage() {}

func (x *AddContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContactResponse.ProtoReflect.Descriptor instead.
func (*AddContactResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{8}
}

type RemoveContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContactRequest) Reset() {
	*x = RemoveContactRequest{}
	mi := &file_ensemble_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContactRequest) ProtoMessage() {}

func (x *RemoveContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContactRequest.ProtoReflect.Descriptor instead.
func (*RemoveContactRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveContactRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RemoveContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContactResponse) Reset() {
	*x = RemoveContactResponse{}
	mi := &file_ensemble_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContactResponse) ProtoMessage() {}

func (x *RemoveContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContactResponse.ProtoReflect.Descriptor instead.
func (*RemoveContactResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{10}
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // peer's ensemble address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_ensemble_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_ensemble_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{12}
}

func (x *ConnectResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AcceptConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // requester's address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptConnectionRequest) Reset() {
	*x = AcceptConnectionRequest{}
	mi := &file_ensemble_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptConnectionRequest) ProtoMessage() {}

func (x *AcceptConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptConnectionRequest.ProtoReflect.Descriptor instead.
func (*AcceptConnectionRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{13}
}

func (x *AcceptConnectionRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AcceptConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptConnectionResponse) Reset() {
	*x = AcceptConnectionResponse{}
	mi := &file_ensemble_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptConnectionResponse) ProtoMessage() {}

func (x *AcceptConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptConnectionResponse.ProtoReflect.Descriptor instead.
func (*AcceptConnectionResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{14}
}

type RejectConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectConnectionRequest) Reset() {
	*x = RejectConnectionRequest{}
	mi := &file_ensemble_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectConnectionRequest) ProtoMessage() {}

func (x *RejectConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectConnectionRequest.ProtoReflect.Descriptor instead.
func (*RejectConnectionRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{15}
}

func (x *RejectConnectionRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RejectConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectConnectionResponse) Reset() {
	*x = RejectConnectionResponse{}
	mi := &file_ensemble_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectConnectionResponse) ProtoMessage() {}

func (x *RejectConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectConnectionResponse.ProtoReflect.Descriptor instead.
func (*RejectConnectionResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{16}
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // recipient's address
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_ensemble_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{17}
}

func (x *SendMessageRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_ensemble_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{18}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SendFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // recipient's address
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_ensemble_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{19}
}

func (x *SendFileRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SendFileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type TransferProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	SentBytes     uint64                 `protobuf:"varint,4,opt,name=sent_bytes,json=sentBytes,proto3" json:"sent_bytes,omitempty"`
	Percent       float32                `protobuf:"fixed32,5,opt,name=percent,proto3" json:"percent,omitempty"`
	Complete      bool                   `protobuf:"varint,6,opt,name=complete,proto3" json:"complete,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferProgress) Reset() {
	*x = TransferProgress{}
	mi := &file_ensemble_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferProgress) ProtoMessage() {}

func (x *TransferProgress) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferProgress.ProtoReflect.Descriptor instead.
func (*TransferProgress) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{20}
}

func (x *TransferProgress) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferProgress) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TransferProgress) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *TransferProgress) GetSentBytes() uint64 {
	if x != nil {
		return x.SentBytes
	}
	return 0
}

func (x *TransferProgress) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *TransferProgress) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *TransferProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AcceptFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	SavePath      string                 `protobuf:"bytes,2,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"` // where to save the file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFileRequest) Reset() {
	*x = AcceptFileRequest{}
	mi := &file_ensemble_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFileRequest) ProtoMessage() {}

func (x *AcceptFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFileRequest.ProtoReflect.Descriptor instead.
func (*AcceptFileRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{21}
}

func (x *AcceptFileRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *AcceptFileRequest) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

type AcceptFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFileResponse) Reset() {
	*x = AcceptFileResponse{}
	mi := &file_ensemble_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFileResponse) ProtoMessage() {}

func (x *AcceptFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFileResponse.ProtoReflect.Descriptor instead.
func (*AcceptFileResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{22}
}

type RejectFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFileRequest) Reset() {
	*x = RejectFileRequest{}
	mi := &file_ensemble_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFileRequest) ProtoMessage() {}

func (x *RejectFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFileRequest.ProtoReflect.Descriptor instead.
func (*RejectFileRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{23}
}

func (x *RejectFileRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type RejectFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectFileResponse) Reset() {
	*x = RejectFileResponse{}
	mi := &file_ensemble_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFileResponse) ProtoMessage() {}

func (x *RejectFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFileResponse.ProtoReflect.Descriptor instead.
func (*RejectFileResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{24}
}

type AddNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnionAddress  string                 `protobuf:"bytes,1,opt,name=onion_address,json=onionAddress,proto3" json:"onion_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_ensemble_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{25}
}

func (x *AddNodeRequest) GetOnionAddress() string {
	if x != nil {
		return x.OnionAddress
	}
	return ""
}

type AddNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeersFound    int32                  `protobuf:"varint,1,opt,name=peers_found,json=peersFound,proto3" json:"peers_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_ensemble_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{26}
}

func (x *AddNodeResponse) GetPeersFound() int32 {
	if x != nil {
		return x.PeersFound
	}
	return 0
}

type GetDebugInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDebugInfoRequest) Reset() {
	*x = GetDebugInfoRequest{}
	mi := &file_ensemble_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebugInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugInfoRequest) ProtoMessage() {}

func (x *GetDebugInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebugInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDebugInfoRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{27}
}

type GetDebugInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RtSize        int32                  `protobuf:"varint,1,opt,name=rt_size,json=rtSize,proto3" json:"rt_size,omitempty"`
	RtPeers       []*DHTNode             `protobuf:"bytes,2,rep,name=rt_peers,json=rtPeers,proto3" json:"rt_peers,omitempty"`
	Connections   []*PeerState           `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
	OnionAddr     string                 `protobuf:"bytes,4,opt,name=onion_addr,json=onionAddr,proto3" json:"onion_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDebugInfoResponse) Reset() {
	*x = GetDebugInfoResponse{}
	mi := &file_ensemble_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebugInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugInfoResponse) ProtoMessage() {}

func (x *GetDebugInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebugInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDebugInfoResponse) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{28}
}

func (x *GetDebugInfoResponse) GetRtSize() int32 {
	if x != nil {
		return x.RtSize
	}
	return 0
}

func (x *GetDebugInfoResponse) GetRtPeers() []*DHTNode {
	if x != nil {
		return x.RtPeers
	}
	return nil
}

func (x *GetDebugInfoResponse) GetConnections() []*PeerState {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *GetDebugInfoResponse) GetOnionAddr() string {
	if x != nil {
		return x.OnionAddr
	}
	return ""
}

type DHTNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OnionAddr     string                 `protobuf:"bytes,2,opt,name=onion_addr,json=onionAddr,proto3" json:"onion_addr,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // Unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DHTNode) Reset() {
	*x = DHTNode{}
	mi := &file_ensemble_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DHTNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHTNode) ProtoMessage() {}

func (x *DHTNode) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHTNode.ProtoReflect.Descriptor instead.
func (*DHTNode) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{29}
}

func (x *DHTNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DHTNode) GetOnionAddr() string {
	if x != nil {
		return x.OnionAddr
	}
	return ""
}

func (x *DHTNode) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type PeerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerState) Reset() {
	*x = PeerState{}
	mi := &file_ensemble_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerState) ProtoMessage() {}

func (x *PeerState) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerState.ProtoReflect.Descriptor instead.
func (*PeerState) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{30}
}

func (x *PeerState) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PeerState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_ensemble_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{31}
}

type DaemonEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // event type name
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded event data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonEvent) Reset() {
	*x = DaemonEvent{}
	mi := &file_ensemble_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonEvent) ProtoMessage() {}

func (x *DaemonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonEvent.ProtoReflect.Descriptor instead.
func (*DaemonEvent) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{32}
}

func (x *DaemonEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DaemonEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ServiceClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServiceClientMessage_Manifest
	//	*ServiceClientMessage_SendMessage
	//	*ServiceClientMessage_Accept
	//	*ServiceClientMessage_Reject
	Msg           isServiceClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceClientMessage) Reset() {
	*x = ServiceClientMessage{}
	mi := &file_ensemble_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceClientMessage) ProtoMessage() {}

func (x *ServiceClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceClientMessage.ProtoReflect.Descriptor instead.
func (*ServiceClientMessage) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{33}
}

func (x *ServiceClientMessage) GetMsg() isServiceClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServiceClientMessage) GetManifest() *ServiceManifest {
	if x != nil {
		if x, ok := x.Msg.(*ServiceClientMessage_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

func (x *ServiceClientMessage) GetSendMessage() *ServiceSendMessage {
	if x != nil {
		if x, ok := x.Msg.(*ServiceClientMessage_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *ServiceClientMessage) GetAccept() *ServiceAcceptConnection {
	if x != nil {
		if x, ok := x.Msg.(*ServiceClientMessage_Accept); ok {
			return x.Accept
		}
	}
	return nil
}

func (x *ServiceClientMessage) GetReject() *ServiceRejectConnection {
	if x != nil {
		if x, ok := x.Msg.(*ServiceClientMessage_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

type isServiceClientMessage_Msg interface {
	isServiceClientMessage_Msg()
}

type ServiceClientMessage_Manifest struct {
	Manifest *ServiceManifest `protobuf:"bytes,1,opt,name=manifest,proto3,oneof"` // first message only
}

type ServiceClientMessage_SendMessage struct {
	SendMessage *ServiceSendMessage `protobuf:"bytes,2,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type ServiceClientMessage_Accept struct {
	Accept *ServiceAcceptConnection `protobuf:"bytes,3,opt,name=accept,proto3,oneof"`
}

type ServiceClientMessage_Reject struct {
	Reject *ServiceRejectConnection `protobuf:"bytes,4,opt,name=reject,proto3,oneof"`
}

func (*ServiceClientMessage_Manifest) isServiceClientMessage_Msg() {}

func (*ServiceClientMessage_SendMessage) isServiceClientMessage_Msg() {}

func (*ServiceClientMessage_Accept) isServiceClientMessage_Msg() {}

func (*ServiceClientMessage_Reject) isServiceClientMessage_Msg() {}

type ServiceServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServiceServerMessage_Registered
	//	*ServiceServerMessage_Event
	//	*ServiceServerMessage_Error
	Msg           isServiceServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceServerMessage) Reset() {
	*x = ServiceServerMessage{}
	mi := &file_ensemble_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceServerMessage) ProtoMessage() {}

func (x *ServiceServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceServerMessage.ProtoReflect.Descriptor instead.
func (*ServiceServerMessage) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{34}
}

func (x *ServiceServerMessage) GetMsg() isServiceServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServiceServerMessage) GetRegistered() *ServiceRegistered {
	if x != nil {
		if x, ok := x.Msg.(*ServiceServerMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *ServiceServerMessage) GetEvent() *ServiceEvent {
	if x != nil {
		if x, ok := x.Msg.(*ServiceServerMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ServiceServerMessage) GetError() *ServiceError {
	if x != nil {
		if x, ok := x.Msg.(*ServiceServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServiceServerMessage_Msg interface {
	isServiceServerMessage_Msg()
}

type ServiceServerMessage_Registered struct {
	Registered *ServiceRegistered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"` // first message only, after manifest accepted
}

type ServiceServerMessage_Event struct {
	Event *ServiceEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type ServiceServerMessage_Error struct {
	Error *ServiceError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ServiceServerMessage_Registered) isServiceServerMessage_Msg() {}

func (*ServiceServerMessage_Event) isServiceServerMessage_Msg() {}

func (*ServiceServerMessage_Error) isServiceServerMessage_Msg() {}

type ServiceManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // slug-safe registry key
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Acl           ACL                    `protobuf:"varint,3,opt,name=acl,proto3,enum=ensemble.api.ACL" json:"acl,omitempty"`
	Allowlist     []string               `protobuf:"bytes,4,rep,name=allowlist,proto3" json:"allowlist,omitempty"`                        // only meaningful when acl == ACL_ALLOWLIST
	KeypairSeed   []byte                 `protobuf:"bytes,5,opt,name=keypair_seed,json=keypairSeed,proto3" json:"keypair_seed,omitempty"` // optional, advisory; ignored if name already has a keypair
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceManifest) Reset() {
	*x = ServiceManifest{}
	mi := &file_ensemble_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceManifest) ProtoMessage() {}

func (x *ServiceManifest) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceManifest.ProtoReflect.Descriptor instead.
func (*ServiceManifest) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{35}
}

func (x *ServiceManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceManifest) GetAcl() ACL {
	if x != nil {
		return x.Acl
	}
	return ACL_ACL_PUBLIC
}

func (x *ServiceManifest) GetAllowlist() []string {
	if x != nil {
		return x.Allowlist
	}
	return nil
}

func (x *ServiceManifest) GetKeypairSeed() []byte {
	if x != nil {
		return x.KeypairSeed
	}
	return nil
}

type ServiceRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // E… Bitcoin-style address
	Onion         string                 `protobuf:"bytes,2,opt,name=onion,proto3" json:"onion,omitempty"`     // .onion endpoint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegistered) Reset() {
	*x = ServiceRegistered{}
	mi := &file_ensemble_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegistered) ProtoMessage() {}

func (x *ServiceRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegistered.ProtoReflect.Descriptor instead.
func (*ServiceRegistered) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{36}
}

func (x *ServiceRegistered) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceRegistered) GetOnion() string {
	if x != nil {
		return x.Onion
	}
	return ""
}

type ServiceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "chat_message", "connection_request"
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // protobuf-encoded payload (see ServiceChatMessageEvent etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEvent) Reset() {
	*x = ServiceEvent{}
	mi := &file_ensemble_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEvent) ProtoMessage() {}

func (x *ServiceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEvent.ProtoReflect.Descriptor instead.
func (*ServiceEvent) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{37}
}

func (x *ServiceEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ServiceChatMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddr      string                 `protobuf:"bytes,1,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"` // Unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceChatMessageEvent) Reset() {
	*x = ServiceChatMessageEvent{}
	mi := &file_ensemble_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceChatMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceChatMessageEvent) ProtoMessage() {}

func (x *ServiceChatMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceChatMessageEvent.ProtoReflect.Descriptor instead.
func (*ServiceChatMessageEvent) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{38}
}

func (x *ServiceChatMessageEvent) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

func (x *ServiceChatMessageEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ServiceChatMessageEvent) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type ServiceConnectionRequestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromAddr      string                 `protobuf:"bytes,2,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConnectionRequestEvent) Reset() {
	*x = ServiceConnectionRequestEvent{}
	mi := &file_ensemble_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConnectionRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConnectionRequestEvent) ProtoMessage() {}

func (x *ServiceConnectionRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConnectionRequestEvent.ProtoReflect.Descriptor instead.
func (*ServiceConnectionRequestEvent) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{39}
}

func (x *ServiceConnectionRequestEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServiceConnectionRequestEvent) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

type ServiceSendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToAddr        string                 `protobuf:"bytes,1,opt,name=to_addr,json=toAddr,proto3" json:"to_addr,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSendMessage) Reset() {
	*x = ServiceSendMessage{}
	mi := &file_ensemble_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSendMessage) ProtoMessage() {}

func (x *ServiceSendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSendMessage.ProtoReflect.Descriptor instead.
func (*ServiceSendMessage) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{40}
}

func (x *ServiceSendMessage) GetToAddr() string {
	if x != nil {
		return x.ToAddr
	}
	return ""
}

func (x *ServiceSendMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ServiceAcceptConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAcceptConnection) Reset() {
	*x = ServiceAcceptConnection{}
	mi := &file_ensemble_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAcceptConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAcceptConnection) ProtoMessage() {}

func (x *ServiceAcceptConnection) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAcceptConnection.ProtoReflect.Descriptor instead.
func (*ServiceAcceptConnection) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{41}
}

func (x *ServiceAcceptConnection) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ServiceRejectConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRejectConnection) Reset() {
	*x = ServiceRejectConnection{}
	mi := &file_ensemble_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRejectConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRejectConnection) ProtoMessage() {}

func (x *ServiceRejectConnection) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRejectConnection.ProtoReflect.Descriptor instead.
func (*ServiceRejectConnection) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{42}
}

func (x *ServiceRejectConnection) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServiceRejectConnection) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ServiceError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceError) Reset() {
	*x = ServiceError{}
	mi := &file_ensemble_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceError) ProtoMessage() {}

func (x *ServiceError) ProtoReflect() protoreflect.Message {
	mi := &file_ensemble_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceError.ProtoReflect.Descriptor instead.
func (*ServiceError) Descriptor() ([]byte, []int) {
	return file_ensemble_proto_rawDescGZIP(), []int{43}
}

func (x *ServiceError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ensemble_proto protoreflect.FileDescriptor

const file_ensemble_proto_rawDesc = "" +
	"\n" +
	"\x0eensemble.proto\x12\fensemble.api\"\x14\n" +
	"\x12GetIdentityRequest\"N\n" +
	"\x13GetIdentityResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\x12\n" +
	"\x10GetStatusRequest\"\xa4\x01\n" +
	"\x11GetStatusResponse\x12\x1b\n" +
	"\ttor_state\x18\x01 \x01(\tR\btorState\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x05R\tpeerCount\x12\x1d\n" +
	"\n" +
	"onion_addr\x18\x03 \x01(\tR\tonionAddr\x12\x1b\n" +
	"\tuptime_ms\x18\x04 \x01(\x03R\buptimeMs\x12\x17\n" +
	"\art_size\x18\x05 \x01(\x05R\x06rtSize\"\x15\n" +
	"\x13ListContactsRequest\"M\n" +
	"\x14ListContactsResponse\x125\n" +
	"\bcontacts\x18\x01 \x03(\v2\x19.ensemble.api.ContactInfoR\bcontacts\"\xd1\x01\n" +
	"\vContactInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12#\n" +
	"\ronion_address\x18\x04 \x01(\tR\fonionAddress\x12\x19\n" +
	"\badded_at\x18\x05 \x01(\x03R\aaddedAt\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\x12\x16\n" +
	"\x06online\x18\a \x01(\bR\x06online\"b\n" +
	"\x11AddContactRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"\x14\n" +
	"\x12AddContactResponse\"0\n" +
	"\x14RemoveContactRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x17\n" +
	"\x15RemoveContactResponse\"*\n" +
	"\x0eConnectRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"G\n" +
	"\x0fConnectResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x17AcceptConnectionRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x1a\n" +
	"\x18AcceptConnectionResponse\"3\n" +
	"\x17RejectConnectionRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x1a\n" +
	"\x18RejectConnectionResponse\"B\n" +
	"\x12SendMessageRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"4\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"H\n" +
	"\x0fSendFileRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\"\xdb\x01\n" +
	"\x10TransferProgress\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"sent_bytes\x18\x04 \x01(\x04R\tsentBytes\x12\x18\n" +
	"\apercent\x18\x05 \x01(\x02R\apercent\x12\x1a\n" +
	"\bcomplete\x18\x06 \x01(\bR\bcomplete\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"Q\n" +
	"\x11AcceptFileRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1b\n" +
	"\tsave_path\x18\x02 \x01(\tR\bsavePath\"\x14\n" +
	"\x12AcceptFileResponse\"4\n" +
	"\x11RejectFileRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"\x14\n" +
	"\x12RejectFileResponse\"5\n" +
	"\x0eAddNodeRequest\x12#\n" +
	"\ronion_address\x18\x01 \x01(\tR\fonionAddress\"2\n" +
	"\x0fAddNodeResponse\x12\x1f\n" +
	"\vpeers_found\x18\x01 \x01(\x05R\n" +
	"peersFound\"\x15\n" +
	"\x13GetDebugInfoRequest\"\xbb\x01\n" +
	"\x14GetDebugInfoResponse\x12\x17\n" +
	"\art_size\x18\x01 \x01(\x05R\x06rtSize\x120\n" +
	"\brt_peers\x18\x02 \x03(\v2\x15.ensemble.api.DHTNodeR\artPeers\x129\n" +
	"\vconnections\x18\x03 \x03(\v2\x17.ensemble.api.PeerStateR\vconnections\x12\x1d\n" +
	"\n" +
	"onion_addr\x18\x04 \x01(\tR\tonionAddr\"_\n" +
	"\aDHTNode\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"onion_addr\x18\x02 \x01(\tR\tonionAddr\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\"Q\n" +
	"\tPeerState\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x12\n" +
	"\x10SubscribeRequest\";\n" +
	"\vDaemonEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"\xa3\x02\n" +
	"\x14ServiceClientMessage\x12;\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1d.ensemble.api.ServiceManifestH\x00R\bmanifest\x12E\n" +
	"\fsend_message\x18\x02 \x01(\v2 .ensemble.api.ServiceSendMessageH\x00R\vsendMessage\x12?\n" +
	"\x06accept\x18\x03 \x01(\v2%.ensemble.api.ServiceAcceptConnectionH\x00R\x06accept\x12?\n" +
	"\x06reject\x18\x04 \x01(\v2%.ensemble.api.ServiceRejectConnectionH\x00R\x06rejectB\x05\n" +
	"\x03msg\"\xc8\x01\n" +
	"\x14ServiceServerMessage\x12A\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2\x1f.ensemble.api.ServiceRegisteredH\x00R\n" +
	"registered\x122\n" +
	"\x05event\x18\x02 \x01(\v2\x1a.ensemble.api.ServiceEventH\x00R\x05event\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x1a.ensemble.api.ServiceErrorH\x00R\x05errorB\x05\n" +
	"\x03msg\"\xad\x01\n" +
	"\x0fServiceManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\x03acl\x18\x03 \x01(\x0e2\x11.ensemble.api.ACLR\x03acl\x12\x1c\n" +
	"\tallowlist\x18\x04 \x03(\tR\tallowlist\x12!\n" +
	"\fkeypair_seed\x18\x05 \x01(\fR\vkeypairSeed\"C\n" +
	"\x11ServiceRegistered\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05onion\x18\x02 \x01(\tR\x05onion\"<\n" +
	"\fServiceEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"Z\n" +
	"\x17ServiceChatMessageEvent\x12\x1b\n" +
	"\tfrom_addr\x18\x01 \x01(\tR\bfromAddr\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\"[\n" +
	"\x1dServiceConnectionRequestEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tfrom_addr\x18\x02 \x01(\tR\bfromAddr\"A\n" +
	"\x12ServiceSendMessage\x12\x17\n" +
	"\ato_addr\x18\x01 \x01(\tR\x06toAddr\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"8\n" +
	"\x17ServiceAcceptConnection\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"P\n" +
	"\x17ServiceRejectConnection\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"(\n" +
	"\fServiceError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*:\n" +
	"\x03ACL\x12\x0e\n" +
	"\n" +
	"ACL_PUBLIC\x10\x00\x12\x10\n" +
	"\fACL_CONTACTS\x10\x01\x12\x11\n" +
	"\rACL_ALLOWLIST\x10\x022\xce\n" +
	"\n" +
	"\x0fEnsembleService\x12R\n" +
	"\vGetIdentity\x12 .ensemble.api.GetIdentityRequest\x1a!.ensemble.api.GetIdentityResponse\x12L\n" +
	"\tGetStatus\x12\x1e.ensemble.api.GetStatusRequest\x1a\x1f.ensemble.api.GetStatusResponse\x12U\n" +
	"\fListContacts\x12!.ensemble.api.ListContactsRequest\x1a\".ensemble.api.ListContactsResponse\x12O\n" +
	"\n" +
	"AddContact\x12\x1f.ensemble.api.AddContactRequest\x1a .ensemble.api.AddContactResponse\x12X\n" +
	"\rRemoveContact\x12\".ensemble.api.RemoveContactRequest\x1a#.ensemble.api.RemoveContactResponse\x12F\n" +
	"\aConnect\x12\x1c.ensemble.api.ConnectRequest\x1a\x1d.ensemble.api.ConnectResponse\x12a\n" +
	"\x10AcceptConnection\x12%.ensemble.api.AcceptConnectionRequest\x1a&.ensemble.api.AcceptConnectionResponse\x12a\n" +
	"\x10RejectConnection\x12%.ensemble.api.RejectConnectionRequest\x1a&.ensemble.api.RejectConnectionResponse\x12R\n" +
	"\vSendMessage\x12 .ensemble.api.SendMessageRequest\x1a!.ensemble.api.SendMessageResponse\x12K\n" +
	"\bSendFile\x12\x1d.ensemble.api.SendFileRequest\x1a\x1e.ensemble.api.TransferProgress0\x01\x12O\n" +
	"\n" +
	"AcceptFile\x12\x1f.ensemble.api.AcceptFileRequest\x1a .ensemble.api.AcceptFileResponse\x12O\n" +
	"\n" +
	"RejectFile\x12\x1f.ensemble.api.RejectFileRequest\x1a .ensemble.api.RejectFileResponse\x12F\n" +
	"\aAddNode\x12\x1c.ensemble.api.AddNodeRequest\x1a\x1d.ensemble.api.AddNodeResponse\x12U\n" +
	"\fGetDebugInfo\x12!.ensemble.api.GetDebugInfoRequest\x1a\".ensemble.api.GetDebugInfoResponse\x12H\n" +
	"\tSubscribe\x12\x1e.ensemble.api.SubscribeRequest\x1a\x19.ensemble.api.DaemonEvent0\x01\x12]\n" +
	"\x0fRegisterService\x12\".ensemble.api.ServiceClientMessage\x1a\".ensemble.api.ServiceServerMessage(\x010\x01B#Z!github.com/boxsie/ensemble/api/pbb\x06proto3"

var (
	file_ensemble_proto_rawDescOnce sync.Once
	file_ensemble_proto_rawDescData []byte
)

func file_ensemble_proto_rawDescGZIP() []byte {
	file_ensemble_proto_rawDescOnce.Do(func() {
		file_ensemble_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ensemble_proto_rawDesc), len(file_ensemble_proto_rawDesc)))
	})
	return file_ensemble_proto_rawDescData
}

var file_ensemble_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ensemble_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_ensemble_proto_goTypes = []any{
	(ACL)(0),                              // 0: ensemble.api.ACL
	(*GetIdentityRequest)(nil),            // 1: ensemble.api.GetIdentityRequest
	(*GetIdentityResponse)(nil),           // 2: ensemble.api.GetIdentityResponse
	(*GetStatusRequest)(nil),              // 3: ensemble.api.GetStatusRequest
	(*GetStatusResponse)(nil),             // 4: ensemble.api.GetStatusResponse
	(*ListContactsRequest)(nil),           // 5: ensemble.api.ListContactsRequest
	(*ListContactsResponse)(nil),          // 6: ensemble.api.ListContactsResponse
	(*ContactInfo)(nil),                   // 7: ensemble.api.ContactInfo
	(*AddContactRequest)(nil),             // 8: ensemble.api.AddContactRequest
	(*AddContactResponse)(nil),            // 9: ensemble.api.AddContactResponse
	(*RemoveContactRequest)(nil),          // 10: ensemble.api.RemoveContactRequest
	(*RemoveContactResponse)(nil),         // 11: ensemble.api.RemoveContactResponse
	(*ConnectRequest)(nil),                // 12: ensemble.api.ConnectRequest
	(*ConnectResponse)(nil),               // 13: ensemble.api.ConnectResponse
	(*AcceptConnectionRequest)(nil),       // 14: ensemble.api.AcceptConnectionRequest
	(*AcceptConnectionResponse)(nil),      // 15: ensemble.api.AcceptConnectionResponse
	(*RejectConnectionRequest)(nil),       // 16: ensemble.api.RejectConnectionRequest
	(*RejectConnectionResponse)(nil),      // 17: ensemble.api.RejectConnectionResponse
	(*SendMessageRequest)(nil),            // 18: ensemble.api.SendMessageRequest
	(*SendMessageResponse)(nil),           // 19: ensemble.api.SendMessageResponse
	(*SendFileRequest)(nil),               // 20: ensemble.api.SendFileRequest
	(*TransferProgress)(nil),              // 21: ensemble.api.TransferProgress
	(*AcceptFileRequest)(nil),             // 22: ensemble.api.AcceptFileRequest
	(*AcceptFileResponse)(nil),            // 23: ensemble.api.AcceptFileResponse
	(*RejectFileRequest)(nil),             // 24: ensemble.api.RejectFileRequest
	(*RejectFileResponse)(nil),            // 25: ensemble.api.RejectFileResponse
	(*AddNodeRequest)(nil),                // 26: ensemble.api.AddNodeRequest
	(*AddNodeResponse)(nil),               // 27: ensemble.api.AddNodeResponse
	(*GetDebugInfoRequest)(nil),           // 28: ensemble.api.GetDebugInfoRequest
	(*GetDebugInfoResponse)(nil),          // 29: ensemble.api.GetDebugInfoResponse
	(*DHTNode)(nil),                       // 30: ensemble.api.DHTNode
	(*PeerState)(nil),                     // 31: ensemble.api.PeerState
	(*SubscribeRequest)(nil),              // 32: ensemble.api.SubscribeRequest
	(*DaemonEvent)(nil),                   // 33: ensemble.api.DaemonEvent
	(*ServiceClientMessage)(nil),          // 34: ensemble.api.ServiceClientMessage
	(*ServiceServerMessage)(nil),          // 35: ensemble.api.ServiceServerMessage
	(*ServiceManifest)(nil),               // 36: ensemble.api.ServiceManifest
	(*ServiceRegistered)(nil),             // 37: ensemble.api.ServiceRegistered
	(*ServiceEvent)(nil),                  // 38: ensemble.api.ServiceEvent
	(*ServiceChatMessageEvent)(nil),       // 39: ensemble.api.ServiceChatMessageEvent
	(*ServiceConnectionRequestEvent)(nil), // 40: ensemble.api.ServiceConnectionRequestEvent
	(*ServiceSendMessage)(nil),            // 41: ensemble.api.ServiceSendMessage
	(*ServiceAcceptConnection)(nil),       // 42: ensemble.api.ServiceAcceptConnection
	(*ServiceRejectConnection)(nil),       // 43: ensemble.api.ServiceRejectConnection
	(*ServiceError)(nil),                  // 44: ensemble.api.ServiceError
}
var file_ensemble_proto_depIdxs = []int32{
	7,  // 0: ensemble.api.ListContactsResponse.contacts:type_name -> ensemble.api.ContactInfo
	30, // 1: ensemble.api.GetDebugInfoResponse.rt_peers:type_name -> ensemble.api.DHTNode
	31, // 2: ensemble.api.GetDebugInfoResponse.connections:type_name -> ensemble.api.PeerState
	36, // 3: ensemble.api.ServiceClientMessage.manifest:type_name -> ensemble.api.ServiceManifest
	41, // 4: ensemble.api.ServiceClientMessage.send_message:type_name -> ensemble.api.ServiceSendMessage
	42, // 5: ensemble.api.ServiceClientMessage.accept:type_name -> ensemble.api.ServiceAcceptConnection
	43, // 6: ensemble.api.ServiceClientMessage.reject:type_name -> ensemble.api.ServiceRejectConnection
	37, // 7: ensemble.api.ServiceServerMessage.registered:type_name -> ensemble.api.ServiceRegistered
	38, // 8: ensemble.api.ServiceServerMessage.event:type_name -> ensemble.api.ServiceEvent
	44, // 9: ensemble.api.ServiceServerMessage.error:type_name -> ensemble.api.ServiceError
	0,  // 10: ensemble.api.ServiceManifest.acl:type_name -> ensemble.api.ACL
	1,  // 11: ensemble.api.EnsembleService.GetIdentity:input_type -> ensemble.api.GetIdentityRequest
	3,  // 12: ensemble.api.EnsembleService.GetStatus:input_type -> ensemble.api.GetStatusRequest
	5,  // 13: ensemble.api.EnsembleService.ListContacts:input_type -> ensemble.api.ListContactsRequest
	8,  // 14: ensemble.api.EnsembleService.AddContact:input_type -> ensemble.api.AddContactRequest
	10, // 15: ensemble.api.EnsembleService.RemoveContact:input_type -> ensemble.api.RemoveContactRequest
	12, // 16: ensemble.api.EnsembleService.Connect:input_type -> ensemble.api.ConnectRequest
	14, // 17: ensemble.api.EnsembleService.AcceptConnection:input_type -> ensemble.api.AcceptConnectionRequest
	16, // 18: ensemble.api.EnsembleService.RejectConnection:input_type -> ensemble.api.RejectConnectionRequest
	18, // 19: ensemble.api.EnsembleService.SendMessage:input_type -> ensemble.api.SendMessageRequest
	20, // 20: ensemble.api.EnsembleService.SendFile:input_type -> ensemble.api.SendFileRequest
	22, // 21: ensemble.api.EnsembleService.AcceptFile:input_type -> ensemble.api.AcceptFileRequest
	24, // 22: ensemble.api.EnsembleService.RejectFile:input_type -> ensemble.api.RejectFileRequest
	26, // 23: ensemble.api.EnsembleService.AddNode:input_type -> ensemble.api.AddNodeRequest
	28, // 24: ensemble.api.EnsembleService.GetDebugInfo:input_type -> ensemble.api.GetDebugInfoRequest
	32, // 25: ensemble.api.EnsembleService.Subscribe:input_type -> ensemble.api.SubscribeRequest
	34, // 26: ensemble.api.EnsembleService.RegisterService:input_type -> ensemble.api.ServiceClientMessage
	2,  // 27: ensemble.api.EnsembleService.GetIdentity:output_type -> ensemble.api.GetIdentityResponse
	4,  // 28: ensemble.api.EnsembleService.GetStatus:output_type -> ensemble.api.GetStatusResponse
	6,  // 29: ensemble.api.EnsembleService.ListContacts:output_type -> ensemble.api.ListContactsResponse
	9,  // 30: ensemble.api.EnsembleService.AddContact:output_type -> ensemble.api.AddContactResponse
	11, // 31: ensemble.api.EnsembleService.RemoveContact:output_type -> ensemble.api.RemoveContactResponse
	13, // 32: ensemble.api.EnsembleService.Connect:output_type -> ensemble.api.ConnectResponse
	15, // 33: ensemble.api.EnsembleService.AcceptConnection:output_type -> ensemble.api.AcceptConnectionResponse
	17, // 34: ensemble.api.EnsembleService.RejectConnection:output_type -> ensemble.api.RejectConnectionResponse
	19, // 35: ensemble.api.EnsembleService.SendMessage:output_type -> ensemble.api.SendMessageResponse
	21, // 36: ensemble.api.EnsembleService.SendFile:output_type -> ensemble.api.TransferProgress
	23, // 37: ensemble.api.EnsembleService.AcceptFile:output_type -> ensemble.api.AcceptFileResponse
	25, // 38: ensemble.api.EnsembleService.RejectFile:output_type -> ensemble.api.RejectFileResponse
	27, // 39: ensemble.api.EnsembleService.AddNode:output_type -> ensemble.api.AddNodeResponse
	29, // 40: ensemble.api.EnsembleService.GetDebugInfo:output_type -> ensemble.api.GetDebugInfoResponse
	33, // 41: ensemble.api.EnsembleService.Subscribe:output_type -> ensemble.api.DaemonEvent
	35, // 42: ensemble.api.EnsembleService.RegisterService:output_type -> ensemble.api.ServiceServerMessage
	27, // [27:43] is the sub-list for method output_type
	11, // [11:27] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ensemble_proto_init() }
func file_ensemble_proto_init() {
	if File_ensemble_proto != nil {
		return
	}
	file_ensemble_proto_msgTypes[33].OneofWrappers = []any{
		(*ServiceClientMessage_Manifest)(nil),
		(*ServiceClientMessage_SendMessage)(nil),
		(*ServiceClientMessage_Accept)(nil),
		(*ServiceClientMessage_Reject)(nil),
	}
	file_ensemble_proto_msgTypes[34].OneofWrappers = []any{
		(*ServiceServerMessage_Registered)(nil),
		(*ServiceServerMessage_Event)(nil),
		(*ServiceServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ensemble_proto_rawDesc), len(file_ensemble_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ensemble_proto_goTypes,
		DependencyIndexes: file_ensemble_proto_depIdxs,
		EnumInfos:         file_ensemble_proto_enumTypes,
		MessageInfos:      file_ensemble_proto_msgTypes,
	}.Build()
	File_ensemble_proto = out.File
	file_ensemble_proto_goTypes = nil
	file_ensemble_proto_depIdxs = nil
}
