# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ensemble_pb2 as ensemble__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ensemble_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnsembleServiceStub(object):
    """--- Service ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentity = channel.unary_unary(
                '/ensemble.api.EnsembleService/GetIdentity',
                request_serializer=ensemble__pb2.GetIdentityRequest.SerializeToString,
                response_deserializer=ensemble__pb2.GetIdentityResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/ensemble.api.EnsembleService/GetStatus',
                request_serializer=ensemble__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=ensemble__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.ListContacts = channel.unary_unary(
                '/ensemble.api.EnsembleService/ListContacts',
                request_serializer=ensemble__pb2.ListContactsRequest.SerializeToString,
                response_deserializer=ensemble__pb2.ListContactsResponse.FromString,
                _registered_method=True)
        self.AddContact = channel.unary_unary(
                '/ensemble.api.EnsembleService/AddContact',
                request_serializer=ensemble__pb2.AddContactRequest.SerializeToString,
                response_deserializer=ensemble__pb2.AddContactResponse.FromString,
                _registered_method=True)
        self.RemoveContact = channel.unary_unary(
                '/ensemble.api.EnsembleService/RemoveContact',
                request_serializer=ensemble__pb2.RemoveContactRequest.SerializeToString,
                response_deserializer=ensemble__pb2.RemoveContactResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/ensemble.api.EnsembleService/Connect',
                request_serializer=ensemble__pb2.ConnectRequest.SerializeToString,
                response_deserializer=ensemble__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.AcceptConnection = channel.unary_unary(
                '/ensemble.api.EnsembleService/AcceptConnection',
                request_serializer=ensemble__pb2.AcceptConnectionRequest.SerializeToString,
                response_deserializer=ensemble__pb2.AcceptConnectionResponse.FromString,
                _registered_method=True)
        self.RejectConnection = channel.unary_unary(
                '/ensemble.api.EnsembleService/RejectConnection',
                request_serializer=ensemble__pb2.RejectConnectionRequest.SerializeToString,
                response_deserializer=ensemble__pb2.RejectConnectionResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/ensemble.api.EnsembleService/SendMessage',
                request_serializer=ensemble__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=ensemble__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.SendFile = channel.unary_stream(
                '/ensemble.api.EnsembleService/SendFile',
                request_serializer=ensemble__pb2.SendFileRequest.SerializeToString,
                response_deserializer=ensemble__pb2.TransferProgress.FromString,
                _registered_method=True)
        self.AcceptFile = channel.unary_unary(
                '/ensemble.api.EnsembleService/AcceptFile',
                request_serializer=ensemble__pb2.AcceptFileRequest.SerializeToString,
                response_deserializer=ensemble__pb2.AcceptFileResponse.FromString,
                _registered_method=True)
        self.RejectFile = channel.unary_unary(
                '/ensemble.api.EnsembleService/RejectFile',
                request_serializer=ensemble__pb2.RejectFileRequest.SerializeToString,
                response_deserializer=ensemble__pb2.RejectFileResponse.FromString,
                _registered_method=True)
        self.AddNode = channel.unary_unary(
                '/ensemble.api.EnsembleService/AddNode',
                request_serializer=ensemble__pb2.AddNodeRequest.SerializeToString,
                response_deserializer=ensemble__pb2.AddNodeResponse.FromString,
                _registered_method=True)
        self.GetDebugInfo = channel.unary_unary(
                '/ensemble.api.EnsembleService/GetDebugInfo',
                request_serializer=ensemble__pb2.GetDebugInfoRequest.SerializeToString,
                response_deserializer=ensemble__pb2.GetDebugInfoResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/ensemble.api.EnsembleService/Subscribe',
                request_serializer=ensemble__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=ensemble__pb2.DaemonEvent.FromString,
                _registered_method=True)
        self.RegisterService = channel.stream_stream(
                '/ensemble.api.EnsembleService/RegisterService',
                request_serializer=ensemble__pb2.ServiceClientMessage.SerializeToString,
                response_deserializer=ensemble__pb2.ServiceServerMessage.FromString,
                _registered_method=True)


class EnsembleServiceServicer(object):
    """--- Service ---

    """

    def GetIdentity(self, request, context):
        """Identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContacts(self, request, context):
        """Contacts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFile(self, request, context):
        """File transfer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNode(self, request, context):
        """Discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDebugInfo(self, request, context):
        """Debug
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterService(self, request_iterator, context):
        """Service registration (multi-service platform)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnsembleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentity,
                    request_deserializer=ensemble__pb2.GetIdentityRequest.FromString,
                    response_serializer=ensemble__pb2.GetIdentityResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=ensemble__pb2.GetStatusRequest.FromString,
                    response_serializer=ensemble__pb2.GetStatusResponse.SerializeToString,
            ),
            'ListContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContacts,
                    request_deserializer=ensemble__pb2.ListContactsRequest.FromString,
                    response_serializer=ensemble__pb2.ListContactsResponse.SerializeToString,
            ),
            'AddContact': grpc.unary_unary_rpc_method_handler(
                    servicer.AddContact,
                    request_deserializer=ensemble__pb2.AddContactRequest.FromString,
                    response_serializer=ensemble__pb2.AddContactResponse.SerializeToString,
            ),
            'RemoveContact': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveContact,
                    request_deserializer=ensemble__pb2.RemoveContactRequest.FromString,
                    response_serializer=ensemble__pb2.RemoveContactResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=ensemble__pb2.ConnectRequest.FromString,
                    response_serializer=ensemble__pb2.ConnectResponse.SerializeToString,
            ),
            'AcceptConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptConnection,
                    request_deserializer=ensemble__pb2.AcceptConnectionRequest.FromString,
                    response_serializer=ensemble__pb2.AcceptConnectionResponse.SerializeToString,
            ),
            'RejectConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectConnection,
                    request_deserializer=ensemble__pb2.RejectConnectionRequest.FromString,
                    response_serializer=ensemble__pb2.RejectConnectionResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=ensemble__pb2.SendMessageRequest.FromString,
                    response_serializer=ensemble__pb2.SendMessageResponse.SerializeToString,
            ),
            'SendFile': grpc.unary_stream_rpc_method_handler(
                    servicer.SendFile,
                    request_deserializer=ensemble__pb2.SendFileRequest.FromString,
                    response_serializer=ensemble__pb2.TransferProgress.SerializeToString,
            ),
            'AcceptFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptFile,
                    request_deserializer=ensemble__pb2.AcceptFileRequest.FromString,
                    response_serializer=ensemble__pb2.AcceptFileResponse.SerializeToString,
            ),
            'RejectFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectFile,
                    request_deserializer=ensemble__pb2.RejectFileRequest.FromString,
                    response_serializer=ensemble__pb2.RejectFileResponse.SerializeToString,
            ),
            'AddNode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNode,
                    request_deserializer=ensemble__pb2.AddNodeRequest.FromString,
                    response_serializer=ensemble__pb2.AddNodeResponse.SerializeToString,
            ),
            'GetDebugInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDebugInfo,
                    request_deserializer=ensemble__pb2.GetDebugInfoRequest.FromString,
                    response_serializer=ensemble__pb2.GetDebugInfoResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ensemble__pb2.SubscribeRequest.FromString,
                    response_serializer=ensemble__pb2.DaemonEvent.SerializeToString,
            ),
            'RegisterService': grpc.stream_stream_rpc_method_handler(
                    servicer.RegisterService,
                    request_deserializer=ensemble__pb2.ServiceClientMessage.FromString,
                    response_serializer=ensemble__pb2.ServiceServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ensemble.api.EnsembleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ensemble.api.EnsembleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnsembleService(object):
    """--- Service ---

    """

    @staticmethod
    def GetIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/GetIdentity',
            ensemble__pb2.GetIdentityRequest.SerializeToString,
            ensemble__pb2.GetIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/GetStatus',
            ensemble__pb2.GetStatusRequest.SerializeToString,
            ensemble__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/ListContacts',
            ensemble__pb2.ListContactsRequest.SerializeToString,
            ensemble__pb2.ListContactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/AddContact',
            ensemble__pb2.AddContactRequest.SerializeToString,
            ensemble__pb2.AddContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/RemoveContact',
            ensemble__pb2.RemoveContactRequest.SerializeToString,
            ensemble__pb2.RemoveContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/Connect',
            ensemble__pb2.ConnectRequest.SerializeToString,
            ensemble__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/AcceptConnection',
            ensemble__pb2.AcceptConnectionRequest.SerializeToString,
            ensemble__pb2.AcceptConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/RejectConnection',
            ensemble__pb2.RejectConnectionRequest.SerializeToString,
            ensemble__pb2.RejectConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/SendMessage',
            ensemble__pb2.SendMessageRequest.SerializeToString,
            ensemble__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ensemble.api.EnsembleService/SendFile',
            ensemble__pb2.SendFileRequest.SerializeToString,
            ensemble__pb2.TransferProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/AcceptFile',
            ensemble__pb2.AcceptFileRequest.SerializeToString,
            ensemble__pb2.AcceptFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/RejectFile',
            ensemble__pb2.RejectFileRequest.SerializeToString,
            ensemble__pb2.RejectFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/AddNode',
            ensemble__pb2.AddNodeRequest.SerializeToString,
            ensemble__pb2.AddNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDebugInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ensemble.api.EnsembleService/GetDebugInfo',
            ensemble__pb2.GetDebugInfoRequest.SerializeToString,
            ensemble__pb2.GetDebugInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ensemble.api.EnsembleService/Subscribe',
            ensemble__pb2.SubscribeRequest.SerializeToString,
            ensemble__pb2.DaemonEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterService(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ensemble.api.EnsembleService/RegisterService',
            ensemble__pb2.ServiceClientMessage.SerializeToString,
            ensemble__pb2.ServiceServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
